export const operatorMap = {
	"eq": "=",
	"neq": "!=",
	"gt": ">",
	"gte": ">=",
	"lt": "<",
	"lte": "<=",
	"like": "LIKE",
	"not_like": "NOT LIKE",
	"is": "IS",
	"is_not": "IS NOT",
	"in": "IN",
	"not_in": "NOT IN",
	"between": "BETWEEN",
	"not_between": "NOT BETWEEN",
	"contains": "@>",
	"contained_by": "<@",
	"has_key": "?",
	"has_keys_any": "?|",
	"has_keys_all": "?&",
}
